import { useState } from "react";
import { FileText } from "lucide-react";
import { PageHeader } from "@/components/common/PageHeader";
import { EmptyState } from "@/components/common/EmptyState";
import { ErrorState } from "@/components/common/ErrorState";
import { Pagination } from "@/components/common/Pagination";
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/Table";
import { TableSkeleton } from "@/components/ui/Skeleton";
import { StatusBadge, Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/Select";
import { useReports } from "@/hooks/useReports";
import { useCursorPagination } from "@/hooks/useCursorPagination";
import type { ReportType } from "@/types/reporting";
import { formatTimestamp } from "@/lib/utils";
import { toast } from "sonner";

const REPORT_TYPES: ReportType[] = ["investigation", "asset", "correlation", "attack_surface", "detection", "executive", "audit"];

export default function Reports() {
  const pagination = useCursorPagination(20);
  const [type, setType] = useState<ReportType | "all">("all");
  const { data, isLoading, isError, error, refetch } = useReports(
    { reportType: type === "all" ? undefined : type },
    pagination.pageParams,
  );

  return (
    <div>
      <PageHeader title="Reports" description="Versioned, citation-validated reports built from this platform's own persisted data." />

      <div className="flex items-center gap-2 border-b border-[color:var(--color-border)] px-6 py-3">
        <Select value={type} onValueChange={(v) => setType(v as ReportType | "all")}>
          <SelectTrigger className="w-48">
            <SelectValue placeholder="Report type" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All report types</SelectItem>
            {REPORT_TYPES.map((t) => (
              <SelectItem key={t} value={t}>{t.replace(/_/g, " ")}</SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      {isError && <ErrorState error={error} onRetry={refetch} />}
      {!isError && isLoading && <TableSkeleton />}
      {!isError && !isLoading && data && data.items.length === 0 && (
        <EmptyState icon={FileText} title="No reports" description="Generate a report via the CLI (ai-recon report create) to see it here." />
      )}
      {!isError && !isLoading && data && data.items.length > 0 && (
        <>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Title</TableHead>
                <TableHead>Type</TableHead>
                <TableHead>Version</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Generated by</TableHead>
                <TableHead>Generated</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {data.items.map((r) => (
                <TableRow key={r.id}>
                  <TableCell className="max-w-xs truncate font-medium">{r.title}</TableCell>
                  <TableCell>{r.reportType.replace(/_/g, " ")}</TableCell>
                  <TableCell><Badge variant="outline">v{r.version}</Badge></TableCell>
                  <TableCell><StatusBadge status={r.status} /></TableCell>
                  <TableCell className="text-[color:var(--color-text-muted)]">{r.generatedBy}</TableCell>
                  <TableCell className="text-[color:var(--color-text-muted)]">{formatTimestamp(r.generatedAt)}</TableCell>
                  <TableCell className="text-right">
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => toast.info("Export requires a connected backend — see docs/reporting/reports.md for the JSON/CSV export contract.")}
                    >
                      Export
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
          <Pagination
            shown={data.items.length}
            hasMore={data.hasMore}
            hasPrev={pagination.hasPrev}
            onNext={() => pagination.next(data.nextCursor)}
            onPrev={pagination.prev}
          />
        </>
      )}
    </div>
  );
}
