package commands

import (
	"fmt"
	"text/tabwriter"
	"time"

	"github.com/google/uuid"
	"github.com/spf13/cobra"

	domainrule "ai-recon-platform/internal/domain/rule"
	"ai-recon-platform/internal/repository/pagination"
	rulerepo "ai-recon-platform/internal/repository/rule"
)

// NewAlertCommand returns the `ai-recon alert` command group — Phase
// 11's analyst-facing alert lifecycle. Resolving/suppressing an alert
// never mutates or deletes the underlying detection match or its
// evidence (phase11.md §20/§21/§35).
func NewAlertCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "alert",
		Short: "List and manage alerts generated by detection rules",
	}
	cmd.AddCommand(newAlertListCommand())
	cmd.AddCommand(newAlertShowCommand())
	cmd.AddCommand(newAlertAcknowledgeCommand())
	cmd.AddCommand(newAlertResolveCommand())
	cmd.AddCommand(newAlertSuppressCommand())
	cmd.AddCommand(newAlertInvestigateCommand())
	return cmd
}

func printAlert(cmd *cobra.Command, a domainrule.Alert) error {
	w := tabwriter.NewWriter(cmd.OutOrStdout(), 0, 4, 2, ' ', 0)
	fmt.Fprintf(w, "ID:\t%s\n", a.ID)                            //nolint:errcheck
	fmt.Fprintf(w, "Title:\t%s\n", a.Title)                      //nolint:errcheck
	fmt.Fprintf(w, "Status:\t%s\n", a.Status)                    //nolint:errcheck
	fmt.Fprintf(w, "Severity:\t%s\n", a.Severity)                //nolint:errcheck
	fmt.Fprintf(w, "Confidence:\t%s\n", a.Confidence)            //nolint:errcheck
	fmt.Fprintf(w, "Detection Match:\t%s\n", a.DetectionMatchID) //nolint:errcheck
	if a.InvestigationID != nil {
		fmt.Fprintf(w, "Investigation:\t%s\n", *a.InvestigationID) //nolint:errcheck
	}
	fmt.Fprintf(w, "First Observed:\t%s\n", a.FirstObservedAt.Format("2006-01-02T15:04:05Z")) //nolint:errcheck
	fmt.Fprintf(w, "Last Observed:\t%s\n", a.LastObservedAt.Format("2006-01-02T15:04:05Z"))   //nolint:errcheck
	return w.Flush()
}

func newAlertListCommand() *cobra.Command {
	var status string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List alerts",
		RunE: func(cmd *cobra.Command, _ []string) error {
			svc, db, err := buildRuleService(cmd)
			if err != nil {
				return err
			}
			defer db.Close()

			page, err := svc.ListAlerts(cmd.Context(), rulerepo.AlertListFilter{
				Status: domainrule.AlertStatus(status), Pagination: pagination.Params{Limit: pagination.MaxLimit},
			})
			if err != nil {
				return err
			}
			w := tabwriter.NewWriter(cmd.OutOrStdout(), 0, 4, 2, ' ', 0)
			fmt.Fprintln(w, "ID\tTITLE\tSTATUS\tSEVERITY\tLAST OBSERVED") //nolint:errcheck
			for _, a := range page.Items {
				fmt.Fprintf(w, "%s\t%s\t%s\t%s\t%s\n", a.ID, a.Title, a.Status, a.Severity, //nolint:errcheck
					a.LastObservedAt.Format("2006-01-02T15:04:05Z"))
			}
			return w.Flush()
		},
	}
	cmd.Flags().StringVar(&status, "status", "", "open|acknowledged|investigating|resolved|suppressed")
	return cmd
}

func newAlertShowCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "show <alert-id>",
		Short: "Show one alert, including its underlying detection match and evidence",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id, err := uuid.Parse(args[0])
			if err != nil {
				return fmt.Errorf("invalid alert id: %w", err)
			}
			svc, db, err := buildRuleService(cmd)
			if err != nil {
				return err
			}
			defer db.Close()

			a, err := svc.GetAlert(cmd.Context(), id)
			if err != nil {
				return err
			}
			if err := printAlert(cmd, a); err != nil {
				return err
			}

			match, err := svc.GetMatch(cmd.Context(), a.DetectionMatchID)
			if err != nil {
				return err
			}
			fmt.Fprintf(cmd.OutOrStdout(), "\n%s\n", match.Explanation) //nolint:errcheck

			evidence, err := svc.ListEvidence(cmd.Context(), match.ID)
			if err != nil {
				return err
			}
			w := tabwriter.NewWriter(cmd.OutOrStdout(), 0, 4, 2, ' ', 0)
			fmt.Fprintln(w, "\nEVIDENCE\tROLE\tOBSERVED AT") //nolint:errcheck
			for _, e := range evidence {
				fmt.Fprintf(w, "%s (%s)\t%s\t%s\n", e.SourceID, e.SourceType, e.Role, //nolint:errcheck
					e.ObservedAt.Format("2006-01-02T15:04:05Z"))
			}
			return w.Flush()
		},
	}
	return cmd
}

func newAlertAcknowledgeCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "acknowledge <alert-id>",
		Short: "Acknowledge an alert",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id, err := uuid.Parse(args[0])
			if err != nil {
				return fmt.Errorf("invalid alert id: %w", err)
			}
			svc, db, err := buildRuleService(cmd)
			if err != nil {
				return err
			}
			defer db.Close()
			a, err := svc.AcknowledgeAlert(cmd.Context(), id)
			if err != nil {
				return err
			}
			return printAlert(cmd, a)
		},
	}
	return cmd
}

func newAlertResolveCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "resolve <alert-id>",
		Short: "Resolve an alert — never mutates or removes its underlying evidence",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id, err := uuid.Parse(args[0])
			if err != nil {
				return fmt.Errorf("invalid alert id: %w", err)
			}
			svc, db, err := buildRuleService(cmd)
			if err != nil {
				return err
			}
			defer db.Close()
			a, err := svc.ResolveAlert(cmd.Context(), id)
			if err != nil {
				return err
			}
			return printAlert(cmd, a)
		},
	}
	return cmd
}

func newAlertSuppressCommand() *cobra.Command {
	var reason, actorID, durationStr string
	cmd := &cobra.Command{
		Use:   "suppress <alert-id>",
		Short: "Suppress an alert (reason required; evidence is never deleted)",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id, err := uuid.Parse(args[0])
			if err != nil {
				return fmt.Errorf("invalid alert id: %w", err)
			}
			if reason == "" || actorID == "" {
				return fmt.Errorf("--reason and --actor are required")
			}
			var duration time.Duration
			if durationStr != "" {
				duration, err = time.ParseDuration(durationStr)
				if err != nil {
					return fmt.Errorf("invalid --duration: %w", err)
				}
			}
			svc, db, err := buildRuleService(cmd)
			if err != nil {
				return err
			}
			defer db.Close()
			a, err := svc.SuppressAlert(cmd.Context(), id, reason, actorID, duration)
			if err != nil {
				return err
			}
			return printAlert(cmd, a)
		},
	}
	cmd.Flags().StringVar(&reason, "reason", "", "why this alert is being suppressed (required)")
	cmd.Flags().StringVar(&actorID, "actor", "", "analyst identifier (required)")
	cmd.Flags().StringVar(&durationStr, "duration", "", "e.g. 30m — omit for indefinite")
	return cmd
}

func newAlertInvestigateCommand() *cobra.Command {
	var actorID string
	cmd := &cobra.Command{
		Use:   "investigate <alert-id>",
		Short: "Promote an alert into a Phase 9 investigation, attaching its evidence and a timeline event automatically",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id, err := uuid.Parse(args[0])
			if err != nil {
				return fmt.Errorf("invalid alert id: %w", err)
			}
			if actorID == "" {
				return fmt.Errorf("--actor is required")
			}
			svc, db, err := buildRuleService(cmd)
			if err != nil {
				return err
			}
			defer db.Close()
			inv, err := svc.PromoteToInvestigation(cmd.Context(), id, actorID)
			if err != nil {
				return err
			}
			fmt.Fprintf(cmd.OutOrStdout(), "Created investigation %s (%q).\n", inv.ID, inv.Title) //nolint:errcheck
			return nil
		},
	}
	cmd.Flags().StringVar(&actorID, "actor", "", "analyst identifier (required)")
	return cmd
}
