package commands

import (
	"fmt"
	"os"
	"strings"
	"text/tabwriter"
	"time"

	"github.com/google/uuid"
	"github.com/spf13/cobra"

	"ai-recon-platform/internal/analytics"
	"ai-recon-platform/internal/database"
	domainreporting "ai-recon-platform/internal/domain/reporting"
	"ai-recon-platform/internal/logging"
	analyticsrepo "ai-recon-platform/internal/repository/analytics"
	assetrepo "ai-recon-platform/internal/repository/asset"
	correlationrepo "ai-recon-platform/internal/repository/correlation"
	findingrepo "ai-recon-platform/internal/repository/finding"
	intelrepo "ai-recon-platform/internal/repository/intelligence"
	investigationrepo "ai-recon-platform/internal/repository/investigation"
	"ai-recon-platform/internal/repository/pagination"
	reportingrepo "ai-recon-platform/internal/repository/reporting"
	rulerepo "ai-recon-platform/internal/repository/rule"
	reportingsvc "ai-recon-platform/internal/service/reporting"
	targetsvc "ai-recon-platform/internal/service/target"
)

// NewReportCommand returns the `ai-recon report` command group —
// Phase 14's reporting engine. Every report is built from Phase 2-13's
// own already-persisted data; nothing here is a duplicate model
// (phase14.md's own "do not create duplicate versions of these
// systems").
func NewReportCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "report",
		Short: "Generate, review, approve, and export security reports",
	}
	cmd.AddCommand(newReportCreateCommand())
	cmd.AddCommand(newReportListCommand())
	cmd.AddCommand(newReportShowCommand())
	cmd.AddCommand(newReportApproveCommand())
	cmd.AddCommand(newReportReviewCommand())
	cmd.AddCommand(newReportExportCommand())
	return cmd
}

// buildReportingService wires a *reportingsvc.Service against a fresh
// database connection. Callers must close the returned *database.Pool.
func buildReportingService(cmd *cobra.Command) (*reportingsvc.Service, *database.Pool, error) {
	cfg, err := loadConfig(cmd)
	if err != nil {
		return nil, nil, fmt.Errorf("configuration is invalid: %w", err)
	}
	logger := logging.New(logging.Options{Level: cfg.Logging.Level, Format: logging.Format(cfg.Logging.Format), Output: os.Stderr})
	db, err := database.Connect(cmd.Context(), cfg.Database)
	if err != nil {
		return nil, nil, err
	}

	analyticsSvc := analytics.NewService(analyticsrepo.NewPostgresRepository(db), analytics.NewCache(analytics.DefaultCacheTTL))

	investigationRepo := investigationrepo.NewPostgresRepository(db)
	assetRepo := assetrepo.NewPostgresRepository(db)
	findingRepo := findingrepo.NewPostgresRepository(db)
	ruleRepo := rulerepo.NewPostgresRepository(db)
	correlationRepo := correlationrepo.NewPostgresRepository(db)
	intelRepo := intelrepo.NewPostgresRepository(db)
	reportingRepo := reportingrepo.NewPostgresRepository(db)

	svc := reportingsvc.NewService(
		db, analyticsSvc,
		investigationRepo, investigationRepo, investigationRepo,
		assetRepo, findingRepo,
		ruleRepo, ruleRepo, ruleRepo,
		correlationRepo, correlationRepo, correlationRepo, correlationRepo, correlationRepo,
		intelRepo, intelRepo,
		reportingRepo, reportingRepo, reportingRepo, reportingRepo,
		logger,
	)
	return svc, db, nil
}

func printReport(cmd *cobra.Command, r domainreporting.Report) {
	w := tabwriter.NewWriter(cmd.OutOrStdout(), 0, 4, 2, ' ', 0)
	fmt.Fprintf(w, "ID:\t%s\n", r.ID)           //nolint:errcheck
	fmt.Fprintf(w, "Type:\t%s\n", r.ReportType) //nolint:errcheck
	if r.SubjectID != nil {
		fmt.Fprintf(w, "Subject:\t%s\n", *r.SubjectID) //nolint:errcheck
	}
	fmt.Fprintf(w, "Version:\t%d\n", r.Version)          //nolint:errcheck
	fmt.Fprintf(w, "Title:\t%s\n", r.Title)              //nolint:errcheck
	fmt.Fprintf(w, "Status:\t%s\n", r.Status)            //nolint:errcheck
	fmt.Fprintf(w, "Content Hash:\t%s\n", r.ContentHash) //nolint:errcheck
	fmt.Fprintf(w, "Generated By:\t%s\n", r.GeneratedBy) //nolint:errcheck
	fmt.Fprintf(w, "Generated At:\t%s\n", r.GeneratedAt) //nolint:errcheck
	if r.ApprovedBy != nil {
		fmt.Fprintf(w, "Approved By:\t%s\n", *r.ApprovedBy) //nolint:errcheck
		fmt.Fprintf(w, "Approved At:\t%s\n", *r.ApprovedAt) //nolint:errcheck
	}
	_ = w.Flush() //nolint:errcheck
}

func newReportCreateCommand() *cobra.Command {
	var targetValue, targetType, reportType, subjectStr, actor string
	rangePreset := "7d"
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Generate a new report (creates a new version if one already exists for this type/subject)",
		RunE: func(cmd *cobra.Command, _ []string) error {
			if actor == "" {
				return fmt.Errorf("--actor is required")
			}
			svc, db, err := buildReportingService(cmd)
			if err != nil {
				return err
			}
			defer db.Close()

			targets := targetsvc.NewService(db)
			target, err := targets.GetByValue(cmd.Context(), resolveCorrelationTargetType(targetType), targetValue)
			if err != nil {
				return err
			}

			var subjectID *uuid.UUID
			if subjectStr != "" {
				id, err := uuid.Parse(subjectStr)
				if err != nil {
					return fmt.Errorf("invalid --subject: %w", err)
				}
				subjectID = &id
			}

			r, err := analytics.ResolveRange(analytics.RangePreset(rangePreset), time.Time{}, time.Time{}, "")
			if err != nil {
				return err
			}

			report, err := svc.Generate(cmd.Context(), reportingsvc.GenerateRequest{
				TargetID: target.ID, ReportType: domainreporting.Type(reportType), SubjectID: subjectID, Range: r, Actor: actor,
			})
			if err != nil {
				return err
			}
			printReport(cmd, report)
			return nil
		},
	}
	cmd.Flags().StringVar(&targetValue, "target", "", "target (required)")
	cmd.Flags().StringVar(&targetType, "target-type", "", "URL|HOST|DOMAIN — defaults to DOMAIN")
	cmd.Flags().StringVar(&reportType, "type", "", "investigation|asset|attack_surface|detection|correlation|executive|audit (required)")
	cmd.Flags().StringVar(&subjectStr, "subject", "", "investigation/asset/correlation id — required for those report types")
	cmd.Flags().StringVar(&actor, "actor", "", "analyst identifier (required)")
	cmd.Flags().StringVar(&rangePreset, "range", "7d", "24h|7d|30d|90d — used by target-wide report types")
	return cmd
}

func newReportListCommand() *cobra.Command {
	var targetValue, targetType, reportType, status string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List reports",
		RunE: func(cmd *cobra.Command, _ []string) error {
			svc, db, err := buildReportingService(cmd)
			if err != nil {
				return err
			}
			defer db.Close()

			filter := reportingrepo.ReportListFilter{
				ReportType: domainreporting.Type(reportType), Status: domainreporting.Status(status),
				Pagination: pagination.Params{Limit: pagination.MaxLimit},
			}
			if targetValue != "" {
				targets := targetsvc.NewService(db)
				target, err := targets.GetByValue(cmd.Context(), resolveCorrelationTargetType(targetType), targetValue)
				if err != nil {
					return err
				}
				filter.TargetID = target.ID
			}
			reports, err := svc.ListReports(cmd.Context(), filter)
			if err != nil {
				return err
			}
			w := tabwriter.NewWriter(cmd.OutOrStdout(), 0, 4, 2, ' ', 0)
			fmt.Fprintln(w, "ID\tTYPE\tVERSION\tSTATUS\tTITLE") //nolint:errcheck
			for _, r := range reports {
				fmt.Fprintf(w, "%s\t%s\t%d\t%s\t%s\n", r.ID, r.ReportType, r.Version, r.Status, r.Title) //nolint:errcheck
			}
			return w.Flush()
		},
	}
	cmd.Flags().StringVar(&targetValue, "target", "", "filter by target")
	cmd.Flags().StringVar(&targetType, "target-type", "", "URL|HOST|DOMAIN — defaults to DOMAIN")
	cmd.Flags().StringVar(&reportType, "type", "", "filter by report type")
	cmd.Flags().StringVar(&status, "status", "", "draft|generated|reviewed|approved")
	return cmd
}

func newReportShowCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "show <id>",
		Short: "Show one report's metadata and content",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id, err := uuid.Parse(args[0])
			if err != nil {
				return fmt.Errorf("invalid report id: %w", err)
			}
			svc, db, err := buildReportingService(cmd)
			if err != nil {
				return err
			}
			defer db.Close()
			r, err := svc.GetReport(cmd.Context(), id)
			if err != nil {
				return err
			}
			printReport(cmd, r)
			fmt.Fprintln(cmd.OutOrStdout(), "\n--- Content (JSON) ---") //nolint:errcheck
			fmt.Fprintln(cmd.OutOrStdout(), r.Content)                  //nolint:errcheck
			return nil
		},
	}
	return cmd
}

func newReportApproveCommand() *cobra.Command {
	var approver, notes string
	cmd := &cobra.Command{
		Use:   "approve <id>",
		Short: "Approve a report — an explicit, distinct analyst action, never automatic",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id, err := uuid.Parse(args[0])
			if err != nil {
				return fmt.Errorf("invalid report id: %w", err)
			}
			if approver == "" {
				return fmt.Errorf("--approver is required")
			}
			svc, db, err := buildReportingService(cmd)
			if err != nil {
				return err
			}
			defer db.Close()
			r, err := svc.Approve(cmd.Context(), id, approver, notes)
			if err != nil {
				return err
			}
			fmt.Fprintf(cmd.OutOrStdout(), "Report %s is now %s.\n", r.ID, r.Status) //nolint:errcheck
			return nil
		},
	}
	cmd.Flags().StringVar(&approver, "approver", "", "analyst identifier (required)")
	cmd.Flags().StringVar(&notes, "notes", "", "optional approval notes")
	return cmd
}

func newReportReviewCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "review <id>",
		Short: "Mark a report reviewed — a step before approval",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id, err := uuid.Parse(args[0])
			if err != nil {
				return fmt.Errorf("invalid report id: %w", err)
			}
			svc, db, err := buildReportingService(cmd)
			if err != nil {
				return err
			}
			defer db.Close()
			r, err := svc.MarkReviewed(cmd.Context(), id)
			if err != nil {
				return err
			}
			fmt.Fprintf(cmd.OutOrStdout(), "Report %s is now %s.\n", r.ID, r.Status) //nolint:errcheck
			return nil
		},
	}
	return cmd
}

func newReportExportCommand() *cobra.Command {
	var format string
	cmd := &cobra.Command{
		Use:   "export <id>",
		Short: "Export a report as JSON or CSV — secrets redacted, values escaped against spreadsheet injection",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			id, err := uuid.Parse(args[0])
			if err != nil {
				return fmt.Errorf("invalid report id: %w", err)
			}
			svc, db, err := buildReportingService(cmd)
			if err != nil {
				return err
			}
			defer db.Close()
			out, err := svc.Export(cmd.Context(), id, strings.ToLower(format))
			if err != nil {
				return err
			}
			_, err = cmd.OutOrStdout().Write(out)
			return err
		},
	}
	cmd.Flags().StringVar(&format, "format", "json", "json|csv")
	return cmd
}
